#!/usr/bin/python

from __future__ import print_function

import os
import shutil
import subprocess
import sys

import portage


GIT_URI = "https://github.com/flatcar/%s.git"
GIT_LOCATION = "/var/lib/portage/%s"


def get_release():
    """Return the version of the currently running release."""
    release = False
    with open("/usr/share/flatcar/release") as release_file:
        for line in release_file:
            if line.startswith("FLATCAR_RELEASE_VERSION="):
                release = line.split("=", 1)[1].strip()

    return release


def get_channel():
    """Return the channel for the current deployment"""
    channel = None
    with open("/usr/share/flatcar/update.conf") as update_conf:
        for line in update_conf:
            if line.startswith("GROUP"):
                channel = line.split("=", 1)[1].strip()
                if channel == 'developer':
                    channel = 'main'

    return channel


def git_clone_repo(repo_url, repo_location):
    """Clone the given repo at the given location"""
    print(">>> Starting git clone in %s" % repo_location)
    os.umask(0o022)
    subprocess.check_call(
        ["git", "clone", "--recurse-submodules", repo_url, repo_location]
    )
    print(">>> Git clone in %s successful" % repo_location)


def sync_repo():
    release = get_release()
    channel = get_channel()
    ref = "%s-%s" % (channel, release)

    repo_list = ["scripts", "coreos-overlay", "portage-stable"]

    for repo in repo_list:
        if os.path.isdir(GIT_LOCATION % repo) and not os.path.islink(
            GIT_LOCATION % repo
        ):
            shutil.rmtree(GIT_LOCATION % repo)
        if os.path.lexists(GIT_LOCATION % repo):
            os.unlink(GIT_LOCATION % repo)

        if repo == "scripts":
            git_clone_repo(
                repo_url=GIT_URI % repo,
                repo_location=GIT_LOCATION % repo,
            )

            subprocess.check_output(
                [
                    "git",
                    "-C",
                    GIT_LOCATION % repo,
                    "checkout",
                    "--recurse-submodules",
                    ref,
                ]
            )
        else:
            print(">>> Symlink the repository with the appropriate folder - %s" % repo)
            os.symlink(
                GIT_LOCATION % "scripts"
                + "/sdk_container/src/third_party/%s" % repo,
                GIT_LOCATION % repo,
            )


def main():
    try:
        sync_repo()
        # Perform normal post-sync tasks
        configroot = portage.settings["PORTAGE_CONFIGROOT"]
        post_sync = "%s/etc/portage/bin/post_sync" % configroot
        if os.path.exists(post_sync):
            subprocess.check_call([post_sync])
        subprocess.check_call(["emerge", "--check-news", "--quiet"])
    except Exception as e:
        print(e.output)
        sys.stderr.write(">>> No git repositories configured.\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
